### ISSUE TITLE
THIS IS 🔥

### ISSUE THREAD

**Issue by todrobbins** [amiaopensource/open-workflows#1]
MOAR OF THIS
PR COMING YOUR WAY

**Comment by ablwr** [comment]
YEEEEHAW!!! Added you to the team too!

**Comment by dericed** [comment]
I appreciate that there's an open issue for how great this repository is.

**Comment by ablwr** [comment]
Secondary issue: Where are @todrobbins's contributions??

**Comment by retokromer** [comment]
🔥🔥🔥

**Comment by ablwr** [comment]
WHERE'S THE FIRE TOD!!!!!

**Comment by kieranjol** [comment]
lol

**Comment by todrobbins** [comment]
Wow. I don't know how I missed the notification a month ago, but I feel sufficiently shamed to make a difference.

**Comment by ablwr** [comment]
👼

**Comment by ablwr** [comment]
@todrobbins

**Comment by ablwr** [comment]
:)

**Comment by todrobbins** [comment]
At least ONE link coming today!

**Comment by ablwr** [comment]
@todrobbins should I close this issue???

**Comment by kieranjol** [comment]
I love this issue so much 🔥

**Comment by todrobbins** [comment]
TOO MUCH PRESSURE

**Comment by todrobbins** [comment]
😉

**Comment by dericed** [comment]
Perhaps a regression, but I'm reopening this issue, because THIS IS STILL 🔥

**Comment by todrobbins** [comment]
hey, check out #22

**Comment by ablwr** [comment]
YEAHH!!!!!!

**Comment by kieranjol** [comment]
:fire: :fire:
