### ISSUE TITLE
"Living will" for home movies - editable docs

### ISSUE THREAD

**Issue by kgrons** [amiaopensource/open-workflows#30]
Would this work best in this repo as a resource, or in analog-inspection? 

From Snowden Becker to the [Home Movie Day](http://www.centerforhomemovies.org/hmd/) (HMD) working group: "a series of editable documents that allow home movie owners/creators document their collections and provide provenance, ownership, and stewardship information."

- [GoogleDocs version](https://docs.google.com/document/d/1wrtQ9Q_s61D2ybc89mZCvGlt9ihqjfFeKhWlAXfZmVU/edit?usp=sharing)
- [HMD blog post](https://snowdenbecker.com/2017/09/25/home-movie-day-2017/) with links to additional editable/fillable formats

"This document is a template people can use to capture content and contextual information about their home movies, designate a caregiver or rights administrator who can act on their behalf, and make their wishes known for how their footage might be accessed and used after being transferred to an archive or other repository. It's shared under a Creative Commons [Creative Commons CC-BY (Attribution)] license, so you can freely adapt or rebrand it for use in your archive or as part of community memory projects."

**Comment by ablwr** [comment]
![image](https://user-images.githubusercontent.com/3260492/31131429-20c6d8c2-a828-11e7-8e28-5d7c691ba28b.png)

**Comment by retokromer** [comment]
I would say here.

**Comment by retokromer** [comment]
>Why don’t have both?

Sorry, I am skeptical about duplicating the resources. On the contrary, I guess we could group some of our resources, and structure their content in «chapters». In my experience, it’s easier to use in the field when only one «thing» has to be loaded/installed.

**Comment by ablwr** [comment]
If this resource is applicable to both open-workflows and analog-inspection, I don't know why it shouldn't be listed in both. They serve different purposes and aren't necessarily both referenced in conjunction with each other at all times.

**Comment by retokromer** [comment]
I am fine either way. Sorry, I was just contributing my personal feeling.
