### ISSUE TITLE
Forced alignment tool

### ISSUE THREAD

**Issue by todrobbins** [amiaopensource/open-workflows#35]
If you think this fits, I'll submit a PR: https://github.com/pettarin/forced-alignment-tools

**Comment by ablwr** [comment]
yea dawg!

**Comment by privatezero** [comment]
Oh rad!! Add it dawg!
![dubs](https://user-images.githubusercontent.com/12941699/32801236-559773de-c931-11e7-9097-dad2cac242ba.jpeg)

**Comment by todrobbins** [comment]
see #37

**Comment by retokromer** [comment]
resolved in https://github.com/amiaopensource/open-workflows/commit/b5f3ddf6023537c7ccf30cf533f40b66b850394d
