### ISSUE TITLE
add a DOI to open-workflows

### ISSUE THREAD

**Issue by laurensorensen** [amiaopensource/open-workflows#44]
Hi there maintainer(s), I would like to cite this project in academic research, and wondering if you'd be willing to attach a DOI to one of the releases. 
There are two services that I've found that can do this, lmk if you need a hand:
http://mozillascience.github.io/code-research-object/
and Zenodo:
https://guides.github.com/activities/citable-code/

Thanks!

**Comment by retokromer** [comment]
@laurensorensen Resolved in https://github.com/amiaopensource/open-workflows/commit/73982de429f917eca3837871e556976f360abb9a.
