### ISSUE TITLE
Some new resources? Elizabeth England/Elvia Arroyo-Ramirez

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/open-workflows#46]
Hey, not sure if these are in scope, but:
https://github.com/jhu-archives-and-manuscripts/homewood-photo/blob/master/HomewoodPhoto_NDSR_FinalReport.pdf
^^ is just stellar documentation and gives a nice sense of a possible born digital workflow in general.

https://medium.com/on-archivy/invisible-defaults-and-perceived-limitations-processing-the-juan-gelman-files-4187fdd36759

^^ Has some excellent practical workflow tips for an archivist, but some brilliant ethical points as well.

**Comment by ablwr** [comment]
Yes I think both of these are very useful!

**Comment by retokromer** [comment]
+1

**Comment by ablwr** [comment]
👋

**Comment by kieranjol** [comment]
Jaysus, I totally forgot about this!will update this weekend!

**Comment by todrobbins** [comment]
@kieranjol we're keeping you accountable! 😉

**Comment by ablwr** [comment]
:eyes:
