### ISSUE TITLE
New section for free published resources

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/open-workflows#47]
I was thinking it might be helpful to include a section for longer published resources that have been made freely available online by their creators. Things like:

* [ARSC Guide](https://www.clir.org/wp-content/uploads/sites/6/pub164.pdf)

* IASA Publications: [TC-03](http://www.iasa-web.org/tc03/ethics-principles-preservation-strategy) Safeguarding the Audio Heritage: Ethics, Principles and Preservation Strategy, [TC-04](http://www.iasa-web.org/tc04/audio-preservation) Guidelines on the Production and Preservation of Digital Audio Objects, [TC-05](http://www.iasa-web.org/handling-storage-tc05) Handling and Storage of Audio and Video Carriers.

* [Sound Directions](http://www.dlib.indiana.edu/projects/sounddirections/papersPresent/sd_bp_07.pdf)

* [DACS](http://files.archivists.org/pubs/DACS2E-2013_v0315.pdf)

Thoughts?

**Comment by ablwr** [comment]
👍

**Comment by retokromer** [comment]
+1

Should those publications be integrated into the existing sections or do you see a special one?

**Comment by privatezero** [comment]
I was thinking a distinct section, maybe `Publications`, as they are not exactly `Documentation` and the scope of the `Resources` section seems a bit more web resource oriented? A `Publications` section might also allow the addition of citations for potentially useful works (such as for the FFmpeg book under recent discussion), even if full download paths could not be provided.

I'll put together a pull and we can see how it fits!

**Comment by ablwr** [comment]
:eyes:

**Comment by privatezero** [comment]
I reckon this could be marked closed via https://github.com/amiaopensource/open-workflows/pull/48

**Comment by ablwr** [comment]
Thank you weaverrrrr!!!!
