### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/open-workflows#76]
Since I have been partially banned from AMIA Open Source, I cannot make myself another release. Could possibly one do it?

**Comment by retokromer** [comment]
Ping!

Could possibly one of @amiaopensource/amia-open-source-governance-team do this, since I am no longer allowed to do it myself?

<img width="1120" alt="Screenshot 2019-03-09 at 06 52 59" src="https://user-images.githubusercontent.com/3246607/54066868-0621f000-4238-11e9-9703-38a28f239cb9.png">

Thank you!

**Comment by ablwr** [comment]
Hi, sure, I can produce a release! As to the permissions issue, that is up to the governance team.

**Comment by retokromer** [comment]
Thank you! This allows to be correctly referenced.

**Comment by dericed** [comment]
Any maintainer of this repo can mark a release. The governance team could possibly do it, but it would be overstepping the repo maintainers to do so.
