### ISSUE TITLE
DAT tape transfer workflow

### ISSUE THREAD

**Issue by smithmyz** [amiaopensource/open-workflows#95]
Hi there!

I have been working on a DAT tape transfer workflow and resource guide as part of my graduate internship with CUNY Television. It focuses specifically on using DDS storage drives to transfer DAT tapes and how to then use the metadata logs created from the transfers for error correction of the resulting audio files. 
As my time with the project comes to a close, my supervisor suggested I contact AMIA opensource to see if there would be any interest in making the final document accessible so it can be shared with the larger community. 
Here is the link to the project: https://docs.google.com/document/d/1NfDFGw_dcmaFkGhHpqZAG6x0DsJ7vceisFcSLNa-Y4k/edit?usp=sharing and hopefully it can be of use!

Thanks so much,
Veronica

**Comment by retokromer** [comment]
Thank you for the hint!

**Comment by ablwr** [comment]
Hi @smithmyz!

Seems like a great addition to this page. Would you like to add it to the README.md? You can use the "edit" (pencil) icon in the corner. It might also be good to save this as a PDF and add it to this repo, just in case something happens to the google docs link.

Let me know if you need any help!

**Comment by smithmyz** [comment]
Great- thanks so much! I'll work on adding it to the README.md/saving it as a PDF and will let you know if I get stuck.

**Comment by retokromer** [comment]
>It might also be good to save this as a PDF and add it to this repo

I suggest to create a dedicated PDF folder as done for the [Time-based media art resources](https://github.com/amiaopensource/time-based-media-art).

**Comment by ablwr** [comment]
Resolved!
